name: Healthcheck

on:
  schedule:
    - cron:  '5 * * * *'
  push:
    branches:
      - master

jobs:
  healthcheck:
    runs-on: ubuntu-18.04
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v1.5
        with:
          url: https://pokedexappjusamankki.herokuapp.com/
          follow-redirect: no # Optional, defaults to "no"
          max-attempts: 3 # Optional, defaults to 1
          retry-delay: 10s # Optional, only applicable to max-attempts > 1
          retry-all: no # Optional, defaults to "no"
